### ISSUE TITLE
Single keys generated

### ISSUE THREAD

**Issue by Philippe734** [OctillionSA/ripple-paper-wallet#3]
Hello,

How to be ensure that the peer private-public key generated are not already used, or will not regenerated, by another person ?

**Comment by ihomp** [comment]
> There are approximately 10^77 points in the curve. The chance that any two people will end up on the same point (i.e. randomly generate same private keypair) for a single keypair generation is 1 in 100,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000
> Even with all the current computing power in the world, finding a collision would take more time than the sun will exist for. 
(c) ToastWallet

ripple-paper-wallet use ripple-lib to randomly generate key pair.
@Philippe734 if you still interested about entropy etc.. check ripple-lib docs.
